### ISSUE TITLE
Kotlin MPP

### ISSUE THREAD

**Issue by Him188** [utybo/Lixy#4]
Thank you for doing such a nice job!
But why not make it MPP? It can create even more possibilities.

**Comment by utybo** [comment]
Hi and thank you! :D

I am not using Kotlin Multiplatform because Kotlin's core Regex class does not have enough features for what Lixy needs.

The specific class that needs Java's Regex class is [this one](https://github.com/utybo/Lixy/blob/master/src/main/kotlin/guru/zoroark/lixy/matchers/RegexPatternRecognizer.kt).

More specifically, the following features are needed:

* `region` to define the exact region that should be considered
* `useTransparentBounds` to allow look-behind and look-ahead to go both beyond the bounds defined by `region`
* `useAnchoringBounds` to have `^` and `$` match the real beginning and end of the string
* `lookingAt`, which checks if the pattern matches when starting at the current index, but does not try to go further if it does not match

**Comment by Him188** [comment]
Thank you, but I think I may have found a solution using Kotlin's `Regex`:
```kotlin
internal class RegexPatternRecognizer(val regexPattern: Regex) :
    LixyTokenRecognizer {
    override fun recognize(s: String, startAt: Int): Pair<String, Int>? {
        return regexPattern.find(s, startAt)
            ?.takeIf { it.range.first == startAt }
            ?.let {
                it.value to it.range.last + 1
            }
    }
}
```
And it have all tests passed.

**Comment by utybo** [comment]
The problem here is that `find` will try to find a match on the entire string, startin from `startAt`, and will use the pattern on *the entire string* until it finds one, whereas `lookingAt` only tests it once at the current spot.

I'll try to investigate this on my side, I don't remember if I had some tests in place for `useAnchoringBounds` and `useTransparentBounds`

**Comment by utybo** [comment]
Maybe it could be done in such a way that:

* On the JVM, use `Pattern` with all the current options
* On other platforms, use `Regex`. It will be slower, but that's better than nothing.

**Comment by utybo** [comment]
Lixy is now a Kotlin MPP! But I still need to fix some build and docs stuff. Progress is being made on the `utybo/mpp` branch.

**Comment by Him188** [comment]
Very nice! Also if you meet something confusing on the experimental MPP, you can refer to my fork [here](https://github.com/Him188/Lixy/tree/mpp). 
There are some incompetable changes so that I won't create a PR.

**Comment by Him188** [comment]
Very nice! Also if you meet something confusing on the experimental MPP, you can refer to my fork [here](https://github.com/Him188/Lixy/tree/mpp). 
There are some incompetable changes so that I won't create a PR.

**Comment by utybo** [comment]
Ah, apologies, I didn't see you were working on it yourself. I like the way you handled the `@Language` annotation, I'll try and see if I can put that in my attempt [when GitHub will be up again](https://www.githubstatus.com/) :D

**Comment by utybo** [comment]
Hi again! Sorry for the delay on this, I got busy with [other projects](https://github.com/EpiLink/EpiLink) 🙂 

I finally got the build and Jitpack working, expect a PR in a few hours to merge this in the master branch! 🎉
